language: php

php:
  - 7.4

services:
  - mysql

stages:
  - check
  - test

cache:
  directories:
    - vendor
jobs:
  include:
    - stage: check
      install:
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
      script:
        - ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no
    - stage: test
      install:
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
      before_script:
        - cp .env.travis .env
        - php artisan key:generate
        - php artisan migrate:fresh --seed
      script:
        - php artisan test
      after_script:
        - rm .env
