version: '3.7'

services:
  app:
    build:
      context: .
      target: dev
      args:
        WWWGROUP: ${WWWGROUP}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-littledivelog.rule=Host(`api.littledivelog.local`)"
      - "traefik.http.routers.api-littledivelog.tls=false"
      - "traefik.http.routers.api-littledivelog.entrypoints=web"
      - "traefik.http.services.api-littledivelog.loadbalancer.server.port=80"
    volumes:
      - .:/www
    environment:
      PHP_IDE_CONFIG: "serverName=api.littledivelog.local"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:alpine
    environment:
    - POSTGRES_USER=littledivelog
    - POSTGRES_DB=littledivelog
    - POSTGRES_PASSWORD=secret
    ports:
    - 5432:5432
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./dev/data:/mnt/data

  typesense:
    image: typesense/typesense:0.24.0.rcn58
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
    volumes:
      - typesense-data:/data
    ports:
      - 8108:8108

  mailhog:
    image: mailhog/mailhog:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail-littledivelog.rule=Host(`mail.littledivelog.local`)"
      - "traefik.http.routers.mail-littledivelog.tls=false"
      - "traefik.http.routers.mail-littledivelog.entrypoints=web"
      - "traefik.http.services.mail-littledivelog.loadbalancer.server.port=8025"
    environment:
      - MH_STORAGE=maildir

  redis:
    image: redis:5-alpine

volumes:
  pg-data:
  typesense-data:

networks:
  default:
    name: littledivelog
    driver: bridge
