version: '3.7'

services:
  app:
    build:
      context: .
      target: dev
      args:
        WWWGROUP: ${WWWGROUP}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-littledivelog.rule=Host(`api.littledivelog.local`)"
      - "traefik.http.routers.api-littledivelog.tls=false"
      - "traefik.http.routers.api-littledivelog.entrypoints=web"
      - "traefik.http.services.api-littledivelog.loadbalancer.server.port=80"
    volumes:
      - .:/www

  db:
    image: postgres:alpine
    environment:
    - POSTGRES_USER=littledivelog
    - POSTGRES_DB=littledivelog
    - POSTGRES_PASSWORD=secret
    ports:
    - 5432:5432
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./dev/data:/mnt/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true


  redis:
    image: redis:5-alpine

volumes:
  pg-data:

networks:
  default:
    name: littledivelog
    driver: bridge
