name: CI

on:
  - push
  - pull_request

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Easy Coding Standard Action
        uses: zingimmick/ecs-action@0.0.4
        with:
          args: --config=dev/ecs.php

  tests:
    name: Tests ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4, 8.0 ]
        experimental: [ false ]
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: littledivelog
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Prepare Env
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate:fresh --seed

      - name: Run tests
        run: php artisan test
